@preconcurrency import ApplicationServices
import AppKit
import Carbon

/// A selected keyword is not proof that an editor supports AXSelectedText writes.
/// Verify the result, and only fall back while that exact selection still belongs to us.
@MainActor
protocol ClipboardSnippetReplacementAccess {
    func originalContextIsValid() -> Bool
    func keywordIsSelected() -> Bool
    func replacementIsPresent() -> Bool
    func replaceUsingAccessibility()
    func pasteReplacement() -> Bool
    func restoreClipboard()
    func restoreSelection()
    func positionCursor()
}

@MainActor
final class ClipboardSnippetReplacementTransaction {
    private let access: any ClipboardSnippetReplacementAccess
    private(set) var didDispatchPaste = false
    private var finished = false

    init(access: any ClipboardSnippetReplacementAccess) { self.access = access }

    func markPasteDispatched() { didDispatchPaste = true }
    func finish() { finished = true }

    /// Run before returning a real input event to the editor, never in a delayed
    /// cancellation cleanup. The access object revalidates focus, text and selection.
    func cancelBeforeForwardingInput() {
        guard !finished else { return }
        if !didDispatchPaste, access.keywordIsSelected() {
            access.restoreSelection()
        }
        // Once paste is posted, let delivery drain without touching the caret or
        // restoring the clipboard early. Do not hold or replay the user's event.
        finished = true
    }
}

@MainActor
enum ClipboardSnippetTextReplacement {
    static func perform(
        using access: any ClipboardSnippetReplacementAccess,
        transaction: ClipboardSnippetReplacementTransaction? = nil,
        pause: @escaping @MainActor () async throws -> Void = { try await Task.sleep(for: .milliseconds(20)) }
    ) async -> Bool {
        var succeeded = false
        defer {
            transaction?.finish()
            access.restoreClipboard()
            if !succeeded && !Task.isCancelled && access.keywordIsSelected() {
                access.restoreSelection()
            }
        }
        // Remote editors can acknowledge a range change before exposing it in AX.
        for _ in 0..<5 where !access.keywordIsSelected() {
            guard !Task.isCancelled, access.originalContextIsValid() else { return false }
            do { try await pause() } catch { return false }
        }
        guard !Task.isCancelled, access.keywordIsSelected() else { return false }
        access.replaceUsingAccessibility()
        // An AX setter can report success while the editor leaves its text unchanged.
        for _ in 0..<5 {
            guard !Task.isCancelled else { return false }
            if access.replacementIsPresent() {
                succeeded = true
                access.positionCursor()
                return true
            }
            do { try await pause() } catch { return false }
        }
        guard !Task.isCancelled, access.keywordIsSelected(), access.pasteReplacement() else { return false }
        transaction?.markPasteDispatched()
        // Once Command-V is posted, cancellation must not immediately restore the
        // clipboard before the destination has read it. No further editor writes
        // occur while this bounded delivery check drains.
        let delivered = await Task { @MainActor in
            for _ in 0..<50 {
                do { try await pause() } catch { return false }
                if access.replacementIsPresent() { return true }
            }
            return false
        }.value
        if delivered && !Task.isCancelled {
            succeeded = true
            access.positionCursor()
            return true
        }
        return false
    }
}

/// Preserves every advertised representation, not just the string. Never restore
/// over a newer copy, and never read password-manager or transient clipboard data.
@MainActor
final class ClipboardSnippetPasteboardLease {
    static let generatedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private let pasteboard: NSPasteboard
    private let originalItems: [NSPasteboardItem]
    private let originalChangeCount: Int
    private var ownedChangeCount: Int?
    private let onWrite: () -> Void

    init?(pasteboard: NSPasteboard, onWrite: @escaping () -> Void) {
        self.pasteboard = pasteboard
        self.onWrite = onWrite
        originalChangeCount = pasteboard.changeCount
        let items = pasteboard.pasteboardItems ?? []
        // Bound temporary backup work; refusing a fallback is safer than losing
        // representations that cannot be materialized or backed up completely.
        guard items.count <= 64,
              items.allSatisfy({ item in
                  item.types.count <= 64 && !item.types.contains(where: {
                      ClipboardCapturePolicy.ignoredProducerTypes.contains($0.rawValue)
                          || $0.rawValue.localizedCaseInsensitiveContains("promise")
                  })
              }) else { return nil }
        var copies: [NSPasteboardItem] = []
        var bytes = 0
        for item in items {
            let copy = NSPasteboardItem()
            for type in item.types {
                guard let data = item.data(forType: type),
                      data.count <= 50 * 1_024 * 1_024 - bytes,
                      copy.setData(data, forType: type) else { return nil }
                bytes += data.count
            }
            copies.append(copy)
        }
        guard pasteboard.changeCount == originalChangeCount else { return nil }
        originalItems = copies
    }

    func write(_ text: String) -> Bool {
        guard ownedChangeCount == nil, pasteboard.changeCount == originalChangeCount else { return false }
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string),
              item.setData(Data(), forType: Self.generatedType) else { return false }
        pasteboard.clearContents()
        ownedChangeCount = pasteboard.changeCount
        let wrote = pasteboard.writeObjects([item])
        ownedChangeCount = pasteboard.changeCount
        onWrite()
        return wrote
    }

    func restore() {
        guard let ownedChangeCount, pasteboard.changeCount == ownedChangeCount else { return }
        self.ownedChangeCount = nil
        pasteboard.clearContents()
        if !originalItems.isEmpty { pasteboard.writeObjects(originalItems) }
        onWrite()
    }
}

@MainActor
final class SystemClipboardSnippetReplacementAccess: ClipboardSnippetReplacementAccess {
    static let syntheticEventMarker: Int64 = 0x4D_54_53_4E_49_50
    let element: AXUIElement
    let processIdentifier: pid_t
    let context: ClipboardSnippetReplacementContext
    let replacement: String
    let cursorLocation: Int?
    let onPasteboardWrite: () -> Void
    private var lease: ClipboardSnippetPasteboardLease?

    init(element: AXUIElement, processIdentifier: pid_t, context: ClipboardSnippetReplacementContext,
         replacement: String, cursorLocation: Int?, onPasteboardWrite: @escaping () -> Void) {
        self.element = element
        self.processIdentifier = processIdentifier
        self.context = context
        self.replacement = replacement
        self.cursorLocation = cursorLocation
        self.onPasteboardWrite = onPasteboardWrite
    }

    private var ownsFocus: Bool {
        guard NSWorkspace.shared.frontmostApplication?.processIdentifier == processIdentifier,
              let focused = ClipboardSnippetKeywordExpander.focusedElement(),
              CFEqual(focused, element),
              ClipboardSnippetKeywordExpander.secureTextClassification(element) == .nonSecure else { return false }
        return true
    }

    func keywordIsSelected() -> Bool {
        guard ownsFocus, let range = ClipboardSnippetKeywordExpander.selectedTextRange(element),
              range.location == context.keywordLocation, range.length == context.keywordLength else { return false }
        return ClipboardSnippetKeywordExpander.string(in: range, of: element) == context.keyword
    }

    func originalContextIsValid() -> Bool {
        guard ownsFocus, let range = ClipboardSnippetKeywordExpander.selectedTextRange(element) else { return false }
        return context.isValid(selection: range, keywordText: ClipboardSnippetKeywordExpander.string(
            in: CFRange(location: context.keywordLocation, length: context.keywordLength), of: element
        ))
    }

    func replacementIsPresent() -> Bool {
        guard ownsFocus, let range = ClipboardSnippetKeywordExpander.selectedTextRange(element),
              range.length == 0, range.location == context.keywordLocation + replacement.utf16.count else { return false }
        return ClipboardSnippetKeywordExpander.string(
            in: CFRange(location: context.keywordLocation, length: replacement.utf16.count), of: element
        ) == replacement
    }

    func replaceUsingAccessibility() {
        guard keywordIsSelected() else { return }
        AXUIElementSetAttributeValue(element, kAXSelectedTextAttribute as CFString, replacement as CFString)
    }

    func pasteReplacement() -> Bool {
        let modifiers: CGEventFlags = [.maskCommand, .maskControl, .maskAlternate, .maskShift]
        guard CGEventSource.flagsState(.combinedSessionState).intersection(modifiers).isEmpty,
              keywordIsSelected(),
              let source = CGEventSource(stateID: .privateState),
              let down = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: false),
              let lease = ClipboardSnippetPasteboardLease(pasteboard: .general, onWrite: onPasteboardWrite),
              keywordIsSelected() else { return false }
        self.lease = lease
        guard lease.write(replacement), keywordIsSelected() else { return false }
        for event in [down, up] {
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: Self.syntheticEventMarker)
            event.postToPid(processIdentifier)
        }
        return true
    }

    func restoreClipboard() { lease?.restore(); lease = nil }

    func restoreSelection() {
        guard keywordIsSelected() else { return }
        setSelection(CFRange(location: context.selectionLocation, length: context.selectionLength))
    }

    func positionCursor() {
        guard let cursorLocation, replacementIsPresent() else { return }
        setSelection(CFRange(location: cursorLocation, length: 0))
    }

    private func setSelection(_ selection: CFRange) {
        var selection = selection
        guard let value = AXValueCreate(.cfRange, &selection) else { return }
        AXUIElementSetAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, value)
    }
}
