import AppKit
import Foundation
import UniformTypeIdentifiers

struct ClipboardPasteboardReaderRequest: Codable, Sendable {
    enum Kind: String, Codable, Sendable {
        case payload
        case plainText
        case semanticText
        case completeSnapshot
    }

    let kind: Kind
    let pasteboardName: String
    let maximumByteCount: Int
    let expectedChangeCount: Int

    init(
        kind: Kind = .payload,
        pasteboardName: String,
        maximumByteCount: Int,
        expectedChangeCount: Int
    ) {
        self.kind = kind
        self.pasteboardName = pasteboardName
        self.maximumByteCount = maximumByteCount
        self.expectedChangeCount = expectedChangeCount
    }
}

struct ClipboardPasteboardReaderResponse: Codable, Sendable {
    enum Status: String, Codable, Equatable, Sendable {
        case payload
        case empty
        case oversized
        case tooManyObjects
        case changed
        case unsafe
    }

    struct Item: Codable, Sendable {
        let representations: [Representation]
    }

    struct Representation: Codable, Sendable {
        let typeIdentifier: String
        let data: Data
    }

    let status: Status
    let items: [Item]

    static func status(_ status: Status) -> Self {
        Self(status: status, items: [])
    }
}

enum ClipboardPasteboardReaderWire {
    static let maximumPasteboardItemCount = 1_024
    static let maximumRepresentationCountPerItem = 64
    static let maximumTotalRepresentationCount = 4_096
    static let maximumSnapshotPasteboardItemCount = 64
    static let maximumRequestFrameByteCount = 64 * 1_024
    static let ignoredProducerTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
    ]

    private static let plainStringTypes: Set<String> = [
        "public.utf8-plain-text",
        "public.file-url",
        "public.url",
    ]
    private static let exactSupportedTypes: Set<String> = [
        "public.utf8-plain-text",
        "public.rtf",
        "com.apple.flat-rtfd",
        "public.html",
        "public.png",
        "public.tiff",
        "com.adobe.pdf",
        "public.file-url",
        "public.url",
        "com.apple.cocoa.pasteboard.color",
        "com.apple.cocoa.pasteboard.sound",
    ]
    private static let semanticTextTypes: Set<String> = [
        "public.utf8-plain-text",
        "public.rtf",
        "com.apple.flat-rtfd",
        "public.html",
    ]

    static func read(_ request: ClipboardPasteboardReaderRequest) -> ClipboardPasteboardReaderResponse {
        let pasteboard = NSPasteboard(name: NSPasteboard.Name(request.pasteboardName))
        guard pasteboard.changeCount == request.expectedChangeCount else {
            return .status(.changed)
        }
        if request.kind == .plainText {
            return readPlainText(from: pasteboard, request: request)
        }
        if request.kind == .semanticText {
            return readSemanticText(from: pasteboard, request: request)
        }
        if request.kind == .completeSnapshot {
            return readCompleteSnapshot(from: pasteboard, request: request)
        }
        guard let sourceItems = pasteboard.pasteboardItems, !sourceItems.isEmpty else {
            return pasteboard.changeCount == request.expectedChangeCount
                ? .status(.empty)
                : .status(.changed)
        }
        guard captureComplexityIsWithinLimits(sourceItems) else {
            return pasteboard.changeCount == request.expectedChangeCount
                ? .status(.tooManyObjects)
                : .status(.changed)
        }

        var storedItems: [ClipboardPasteboardReaderResponse.Item] = []
        var storedByteCount = 0
        for sourceItem in sourceItems {
            if let fileRepresentation = fileURLRepresentation(from: sourceItem) {
                guard fileRepresentation.data.count <= request.maximumByteCount - storedByteCount else {
                    return .status(.oversized)
                }
                storedByteCount += fileRepresentation.data.count
                storedItems.append(.init(representations: [fileRepresentation]))
                continue
            }

            var representations: [ClipboardPasteboardReaderResponse.Representation] = []
            var seenTypes = Set<String>()
            for type in sourceItem.types where seenTypes.insert(type.rawValue).inserted {
                let typeIdentifier = type.rawValue
                guard isSupported(typeIdentifier) else { continue }
                let data: Data?
                if plainStringTypes.contains(typeIdentifier) {
                    data = sourceItem.string(forType: type).map { Data($0.utf8) }
                } else {
                    data = sourceItem.data(forType: type)
                }
                guard let data, !data.isEmpty else { continue }
                guard data.count <= request.maximumByteCount - storedByteCount else {
                    return .status(.oversized)
                }
                storedByteCount += data.count
                representations.append(.init(typeIdentifier: typeIdentifier, data: data))
            }
            if !representations.isEmpty {
                storedItems.append(.init(representations: representations))
            }
        }

        guard pasteboard.changeCount == request.expectedChangeCount else {
            return .status(.changed)
        }
        guard !storedItems.isEmpty else { return .status(.empty) }
        return ClipboardPasteboardReaderResponse(status: .payload, items: storedItems)
    }

    private static func readCompleteSnapshot(
        from pasteboard: NSPasteboard,
        request: ClipboardPasteboardReaderRequest
    ) -> ClipboardPasteboardReaderResponse {
        guard let sourceItems = pasteboard.pasteboardItems, !sourceItems.isEmpty else {
            return pasteboard.changeCount == request.expectedChangeCount
                ? .status(.empty)
                : .status(.changed)
        }
        guard snapshotComplexityIsWithinLimits(sourceItems) else {
            return pasteboard.changeCount == request.expectedChangeCount
                ? .status(.tooManyObjects)
                : .status(.changed)
        }
        let sourceTypes = Set(sourceItems.flatMap(\.types).map(\.rawValue))
        guard sourceTypes.isDisjoint(with: ignoredProducerTypes),
              !sourceTypes.contains(where: {
                  $0.localizedCaseInsensitiveContains("promise")
              }) else {
            return .status(.unsafe)
        }

        var storedItems: [ClipboardPasteboardReaderResponse.Item] = []
        var storedByteCount = 0
        let maximumByteCount = max(0, request.maximumByteCount)
        for sourceItem in sourceItems {
            var representations: [ClipboardPasteboardReaderResponse.Representation] = []
            var seenTypes = Set<String>()
            for type in sourceItem.types where seenTypes.insert(type.rawValue).inserted {
                guard let data = sourceItem.data(forType: type),
                      data.count <= maximumByteCount - storedByteCount else {
                    return .status(.oversized)
                }
                storedByteCount += data.count
                representations.append(.init(typeIdentifier: type.rawValue, data: data))
            }
            storedItems.append(.init(representations: representations))
        }

        guard pasteboard.changeCount == request.expectedChangeCount else {
            return .status(.changed)
        }
        return ClipboardPasteboardReaderResponse(status: .payload, items: storedItems)
    }

    private static func readPlainText(
        from pasteboard: NSPasteboard,
        request: ClipboardPasteboardReaderRequest
    ) -> ClipboardPasteboardReaderResponse {
        guard let sourceItems = pasteboard.pasteboardItems, !sourceItems.isEmpty else {
            return pasteboard.changeCount == request.expectedChangeCount
                ? .status(.empty)
                : .status(.changed)
        }
        guard captureComplexityIsWithinLimits(sourceItems) else {
            return pasteboard.changeCount == request.expectedChangeCount
                ? .status(.tooManyObjects)
                : .status(.changed)
        }
        let sourceTypes = Set(sourceItems.flatMap(\.types).map(\.rawValue))
        guard sourceTypes.isDisjoint(with: ignoredProducerTypes) else {
            return .status(.unsafe)
        }
        guard let text = pasteboard.string(forType: .string) else {
            return pasteboard.changeCount == request.expectedChangeCount
                ? .status(.empty)
                : .status(.changed)
        }
        guard pasteboard.changeCount == request.expectedChangeCount else {
            return .status(.changed)
        }
        let data = Data(text.utf8)
        guard data.count <= max(0, request.maximumByteCount) else {
            return .status(.oversized)
        }
        return ClipboardPasteboardReaderResponse(
            status: .payload,
            items: [.init(representations: [
                .init(typeIdentifier: "public.utf8-plain-text", data: data),
            ])]
        )
    }

    private static func readSemanticText(
        from pasteboard: NSPasteboard,
        request: ClipboardPasteboardReaderRequest
    ) -> ClipboardPasteboardReaderResponse {
        guard let sourceItems = pasteboard.pasteboardItems, !sourceItems.isEmpty else {
            return pasteboard.changeCount == request.expectedChangeCount
                ? .status(.empty)
                : .status(.changed)
        }
        guard captureComplexityIsWithinLimits(sourceItems) else {
            return pasteboard.changeCount == request.expectedChangeCount
                ? .status(.tooManyObjects)
                : .status(.changed)
        }
        let sourceTypes = Set(sourceItems.flatMap(\.types).map(\.rawValue))
        guard sourceTypes.isDisjoint(with: ignoredProducerTypes) else {
            return .status(.unsafe)
        }

        var storedItems: [ClipboardPasteboardReaderResponse.Item] = []
        var storedByteCount = 0
        let maximumByteCount = max(0, request.maximumByteCount)
        for sourceItem in sourceItems {
            var representations: [ClipboardPasteboardReaderResponse.Representation] = []
            var seenTypes = Set<String>()
            let orderedTypes = sourceItem.types.sorted { lhs, rhs in
                lhs.rawValue == "public.utf8-plain-text"
                    && rhs.rawValue != "public.utf8-plain-text"
            }
            for type in orderedTypes where seenTypes.insert(type.rawValue).inserted {
                let typeIdentifier = type.rawValue
                guard semanticTextTypes.contains(typeIdentifier) else { continue }
                let data: Data?
                if typeIdentifier == "public.utf8-plain-text" {
                    data = sourceItem.string(forType: type).map { Data($0.utf8) }
                } else {
                    data = sourceItem.data(forType: type)
                }
                guard let data, !data.isEmpty else { continue }
                guard data.count <= maximumByteCount - storedByteCount else {
                    if typeIdentifier == "public.utf8-plain-text" {
                        return .status(.oversized)
                    }
                    continue
                }
                storedByteCount += data.count
                representations.append(.init(typeIdentifier: typeIdentifier, data: data))
            }
            if !representations.isEmpty {
                storedItems.append(.init(representations: representations))
            }
        }

        guard pasteboard.changeCount == request.expectedChangeCount else {
            return .status(.changed)
        }
        guard !storedItems.isEmpty else { return .status(.empty) }
        return ClipboardPasteboardReaderResponse(status: .payload, items: storedItems)
    }

    static func captureComplexityIsWithinLimits(_ sourceItems: [NSPasteboardItem]) -> Bool {
        guard sourceItems.count <= maximumPasteboardItemCount else { return false }
        var totalRepresentationCount = 0
        for sourceItem in sourceItems {
            guard sourceItem.types.count <= maximumRepresentationCountPerItem else { return false }
            totalRepresentationCount += sourceItem.types.count
            guard totalRepresentationCount <= maximumTotalRepresentationCount else { return false }
        }
        return true
    }

    private static func snapshotComplexityIsWithinLimits(_ sourceItems: [NSPasteboardItem]) -> Bool {
        guard sourceItems.count <= maximumSnapshotPasteboardItemCount else { return false }
        return captureComplexityIsWithinLimits(sourceItems)
    }

    static func encode<T: Encodable>(_ value: T) throws -> Data {
        let encoder = PropertyListEncoder()
        encoder.outputFormat = .binary
        return try encoder.encode(value)
    }

    static func decode<T: Decodable>(_ type: T.Type, from data: Data) throws -> T {
        try PropertyListDecoder().decode(type, from: data)
    }

    static func writeFrame(_ data: Data, to handle: FileHandle) throws {
        var length = UInt64(data.count).bigEndian
        let header = withUnsafeBytes(of: &length) { Data($0) }
        try handle.write(contentsOf: header)
        try handle.write(contentsOf: data)
    }

    static func readFrame(from handle: FileHandle, maximumByteCount: Int) throws -> Data {
        let header = try readExactly(8, from: handle)
        let length = header.reduce(UInt64(0)) { ($0 << 8) | UInt64($1) }
        guard length <= UInt64(maximumByteCount) else {
            throw ClipboardPasteboardReaderWireError.frameTooLarge
        }
        return try readExactly(Int(length), from: handle)
    }

    private static func readExactly(_ count: Int, from handle: FileHandle) throws -> Data {
        var data = Data()
        data.reserveCapacity(count)
        while data.count < count {
            guard let chunk = try handle.read(upToCount: count - data.count), !chunk.isEmpty else {
                throw ClipboardPasteboardReaderWireError.unexpectedEndOfFile
            }
            data.append(chunk)
        }
        return data
    }

    private static func isSupported(_ typeIdentifier: String) -> Bool {
        if exactSupportedTypes.contains(typeIdentifier) { return true }
        guard let type = UTType(typeIdentifier) else { return false }
        return type.conforms(to: .image)
            || type.conforms(to: .audio)
            || type.conforms(to: .movie)
    }

    private static func fileURLRepresentation(
        from sourceItem: NSPasteboardItem
    ) -> ClipboardPasteboardReaderResponse.Representation? {
        let type = NSPasteboard.PasteboardType("public.file-url")
        guard sourceItem.types.contains(type),
              let value = sourceItem.string(forType: type),
              let url = URL(string: value.trimmingCharacters(in: .whitespacesAndNewlines)),
              url.isFileURL else {
            return nil
        }
        return .init(typeIdentifier: "public.file-url", data: Data(url.absoluteString.utf8))
    }
}

enum ClipboardPasteboardReaderWireError: Error {
    case frameTooLarge
    case unexpectedEndOfFile
}
